In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df_products = pd.read_csv('../data/raw/products.csv')

In [4]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [5]:
df_products.columns

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices'], dtype='str')

In [6]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  str
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.9 MB

In [7]:
df_products['prices'].describe()

count    49693.000000
mean         9.994136
std        453.519686
min          1.000000
25%          4.100000
50%          7.100000
75%         11.200000
max      99999.000000
Name: prices, dtype: float64

In [8]:
df_departments = pd.read_csv("../data/raw/departments.csv")
df_departments.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [11]:
df_dep_t = df_departments.T

In [12]:
df_dep_t.reset_index(inplace=True)

In [18]:
df_dep_t.head()

           index           0
0  department_id  department
1              1      frozen
2              2       other
3              3      bakery
4              4     produce

In [20]:
new_header = df_dep_t.iloc[0]
print(new_header)

index    department_id
0           department
Name: 0, dtype: str

In [17]:
df_dep_t_new = df_dep_t[1:]
df_dep_t_new.head()

  index        0
1     1   frozen
2     2    other
3     3   bakery
4     4  produce
5     5  alcohol

In [21]:
df_dep_t_new.columns = new_header   
df_dep_t_new.reset_index(inplace=True, drop=True)

df_dep_t_new.head()

0 department_id department
0             1     frozen
1             2      other
2             3     bakery
3             4    produce
4             5    alcohol

In [22]:
df_dep_t_new.to_csv("../data/processed/departments_t.csv", index=False)

In [25]:
import pandas as pd
from pathlib import Path

# Define relative path to the data folder from scripts/
file_path = Path("../data/raw") / "aisles.csv"

# Read the CSV file
df = pd.read_csv(file_path)

# Display the first few rows
print(df.head())

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

# Try on my project data

In [ ]:
df_coffee_shop_transactions = pd.read_csv('../data/coffee_shop_transactions.csv')

In [ ]:
df_coffee_shop_transactions.head()

,transaction_id,date,time,quantity,unit_price,store_id,product_variant_id
0,36915,2023-03-05,17:15:40,1,2.50,8,48
1,14288,2023-01-25,19:13:00,2,4.75,3,61
2,24597,2023-02-13,12:22:58,1,3.50,8,76
3,22035,2023-02-09,09:36:48,2,2.50,5,50
4,26777,2023-02-17,08:36:03,1,3.75,8,79

In [ ]:
df_coffee_shop_transactions['unit_price'].describe()