# Imports

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
from utils_plotly import *

# Dummy Data

In [2]:
np.random.seed(42)

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()
df_plotly["month"].dtype

dtype('<M8[us]')

# Bar Plot

In [3]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [4]:
# fig =px.bar(
#     data_frame=region_sales,
#     x="region",
#     y="sales",
#     text="sales",
#     title="Total Sales by Region",
# )

# fig.update_traces(
#     textposition="outside",
# )

# fig.update_layout(
#     xaxis_title="",
#     yaxis_title="Total Sales",
# )

# Using my plotly function
fig = my_bar_chart(
    data=region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    x_title="",
    y_title="Total Sales",
    top = False
)

fig.show()

# Line Chart

In [5]:
monthly_sales = (
    df_plotly.groupby("month", as_index=False)["sales"]
             .sum()
)
# df_plotly.head()
monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [6]:
fig = my_line_chart(
    data=monthly_sales,
    x="month",
    y="sales",
    title="Total Sales by Month",
    x_title="",
    y_title="Total Sales",
    markers=True
)

fig.show()

# Hystogram

In [14]:
fig = px.histogram(
    df_plotly,
    x="sales",
    nbins=15,
    title="Distribution of Sales",
)

fig.update_layout(
    xaxis_title="Sales",
    yaxis_title="Count"
)

fig.show()

# Scatter Plot

In [ ]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    hover_data=["product", "month_name", "units"],
    title="Customers vs Sales",
    size="units",
)

fig.update_layout(
    xaxis_title="Customers",
    yaxis_title="Sales",
    legend_title="Region",
)

fig.show()